[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"
  HUGO_VERSION = "0.55.6"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"

[[redirects]]
  from = "https://www.noblenurses.net/cpr-bls-acls-pals-lexington-ky"
  to = "https://www.noblenurses.net/aha-cpr-bls-acls-pals-lexington-kentucky"
  status = 301
  force = true #COMMENT: ensure that we always redirect

[[redirects]]
  from = "https://www.noblenurses.net/service-pricing"
  to = "https://www.noblenurses.net/aha-cpr-bls-acls-pals-lexington-kentucky"
  status = 301
  force = true #COMMENT: ensure that we always redirect

[[redirects]]
  from = "https://www.noblenurses.net/blank-page-1"
  to = "https://www.noblenurses.net/about"
  status = 301
  force = true #COMMENT: ensure that we always redirect

[[redirects]]
  from = "https://www.noblenurses.net/blank-page"
  to = "https://www.noblenurses.net/testimonials"
  status = 301
  force = true #COMMENT: ensure that we always redirect

[[redirects]]
  from = "https://www.noblenurses.net/write-a-review"
  to = "https://search.google.com/local/writereview?placeid=ChIJ90A7o6VPQogRVuyUoGNEonc"
  status = 301
  force = true #COMMENT: ensure that we always redirect